// export const TOGGLE_CHAPTER = 'TOGGLE_CHAPTER'
// export const ADD_CHAPTER = 'ADD_CHAPTER'
export const ADD_SECTION = 'ADD_SECTION'
export const TOGGLE_SECTION = 'TOGGLE_SECTION'

// export const FETCH_CHAPTER_REQUEST = 'FETCH_CHAPTER_REQUEST'
// export const FETCH_CHAPTER_SUCCESS = 'FETCH_CHAPTER_SUCCESS'
// export const FETCH_CHAPTER_FAILURE = 'FETCH_CHAPTER_FAILURE'
